CREATE TABLE IF NOT EXISTS `films`.`film_list`(
	FID INTEGER PRIMARY KEY AUTOINCREMENT,
	ORIG_NAME VARCHAR(255) NOT NULL DEFAULT 'film_name',
	TRANSLATED_NAME NVARCHAR(255) NOT NULL DEFAULT 'film_name_translated',
	GENRE NVARCHAR(255) NOT NULL DEFAULT 'триллер',
	DATE_CREATING INT NOT NULL DEFAULT '2013',
);
PRAGMA encoding = UTF-8;
